name: test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-13, macos-14, macos-15 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v5

    - name: setup sparkle
      uses: ./
      with:
        version: 2.8.0

    - name: show tools
      run: ls -la "$SPARKLE_BIN"

    - name: run generate_appcast
      run: generate_appcast -h
