name: test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-11, macos-12, macos-13 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup sparkle
      uses: ./
      with:
        version: 2.6.2

    - name: show tools
      run: ls -la "$SPARKLE_BIN"

    - name: run generate_appcast
      run: generate_appcast -h
